// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: test_server.proto

package mock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_test_server_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_test_server_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type OTelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OTelRequest) Reset() {
	*x = OTelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OTelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTelRequest) ProtoMessage() {}

func (x *OTelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTelRequest.ProtoReflect.Descriptor instead.
func (*OTelRequest) Descriptor() ([]byte, []int) {
	return file_test_server_proto_rawDescGZIP(), []int{2}
}

type OTelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trace   string `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	Baggage string `protobuf:"bytes,2,opt,name=baggage,proto3" json:"baggage,omitempty"`
}

func (x *OTelResponse) Reset() {
	*x = OTelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OTelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTelResponse) ProtoMessage() {}

func (x *OTelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTelResponse.ProtoReflect.Descriptor instead.
func (*OTelResponse) Descriptor() ([]byte, []int) {
	return file_test_server_proto_rawDescGZIP(), []int{3}
}

func (x *OTelResponse) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

func (x *OTelResponse) GetBaggage() string {
	if x != nil {
		return x.Baggage
	}
	return ""
}

var File_test_server_proto protoreflect.FileDescriptor

var file_test_server_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x24, 0x72, 0x65, 0x61, 0x74, 0x61, 0x6e, 0x67, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x68, 0x70, 0x5f, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x73, 0x2e, 0x6d, 0x6f, 0x63, 0x6b, 0x22, 0x21, 0x0a, 0x0b, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x22, 0x0a, 0x0c,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67,
	0x22, 0x0d, 0x0a, 0x0b, 0x4f, 0x54, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x3e, 0x0a, 0x0c, 0x4f, 0x54, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x67, 0x67, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x67, 0x67, 0x61, 0x67, 0x65, 0x32,
	0xea, 0x01, 0x0a, 0x0a, 0x54, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x6d,
	0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x31, 0x2e, 0x72, 0x65, 0x61, 0x74, 0x61, 0x6e, 0x67,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x68, 0x70, 0x5f, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x72, 0x65, 0x61, 0x74,
	0x61, 0x6e, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x68, 0x70, 0x5f, 0x61, 0x62, 0x73,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x6d, 0x6f, 0x63, 0x6b,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a,
	0x04, 0x4f, 0x54, 0x65, 0x6c, 0x12, 0x31, 0x2e, 0x72, 0x65, 0x61, 0x74, 0x61, 0x6e, 0x67, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x68, 0x70, 0x5f, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x4f, 0x54, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x72, 0x65, 0x61, 0x74, 0x61,
	0x6e, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x68, 0x70, 0x5f, 0x61, 0x62, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x6d, 0x6f, 0x63, 0x6b, 0x2e,
	0x4f, 0x54, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x5b, 0x5a, 0x06,
	0x2e, 0x2f, 0x6d, 0x6f, 0x63, 0x6b, 0xc2, 0x02, 0x03, 0x50, 0x42, 0x5c, 0xca, 0x02, 0x22, 0x52,
	0x65, 0x61, 0x74, 0x61, 0x6e, 0x67, 0x5c, 0x47, 0x72, 0x70, 0x63, 0x50, 0x48, 0x50, 0x41, 0x62,
	0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5c, 0x54, 0x65, 0x73, 0x74, 0x73, 0x5c, 0x4d, 0x6f, 0x63,
	0x6b, 0xd0, 0x02, 0x01, 0xe2, 0x02, 0x22, 0x52, 0x65, 0x61, 0x74, 0x61, 0x6e, 0x67, 0x5c, 0x47,
	0x72, 0x70, 0x63, 0x50, 0x48, 0x50, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5c, 0x54,
	0x65, 0x73, 0x74, 0x73, 0x5c, 0x4d, 0x6f, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_test_server_proto_rawDescOnce sync.Once
	file_test_server_proto_rawDescData = file_test_server_proto_rawDesc
)

func file_test_server_proto_rawDescGZIP() []byte {
	file_test_server_proto_rawDescOnce.Do(func() {
		file_test_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_server_proto_rawDescData)
	})
	return file_test_server_proto_rawDescData
}

var file_test_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test_server_proto_goTypes = []interface{}{
	(*PingRequest)(nil),  // 0: reatang.grpc_php_abstract.tests.mock.PingRequest
	(*PingResponse)(nil), // 1: reatang.grpc_php_abstract.tests.mock.PingResponse
	(*OTelRequest)(nil),  // 2: reatang.grpc_php_abstract.tests.mock.OTelRequest
	(*OTelResponse)(nil), // 3: reatang.grpc_php_abstract.tests.mock.OTelResponse
}
var file_test_server_proto_depIdxs = []int32{
	0, // 0: reatang.grpc_php_abstract.tests.mock.TestServer.Ping:input_type -> reatang.grpc_php_abstract.tests.mock.PingRequest
	2, // 1: reatang.grpc_php_abstract.tests.mock.TestServer.OTel:input_type -> reatang.grpc_php_abstract.tests.mock.OTelRequest
	1, // 2: reatang.grpc_php_abstract.tests.mock.TestServer.Ping:output_type -> reatang.grpc_php_abstract.tests.mock.PingResponse
	3, // 3: reatang.grpc_php_abstract.tests.mock.TestServer.OTel:output_type -> reatang.grpc_php_abstract.tests.mock.OTelResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_server_proto_init() }
func file_test_server_proto_init() {
	if File_test_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OTelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OTelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_server_proto_goTypes,
		DependencyIndexes: file_test_server_proto_depIdxs,
		MessageInfos:      file_test_server_proto_msgTypes,
	}.Build()
	File_test_server_proto = out.File
	file_test_server_proto_rawDesc = nil
	file_test_server_proto_goTypes = nil
	file_test_server_proto_depIdxs = nil
}
