<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_server.proto

namespace Reatang\GrpcPHPAbstract\Tests\Mock\PB;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>reatang.grpc_php_abstract.tests.mock.OtelResponse</code>
 */
class OtelResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string trace = 1;</code>
     */
    protected $trace = '';
    /**
     * Generated from protobuf field <code>string baggage = 2;</code>
     */
    protected $baggage = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $trace
     *     @type string $baggage
     * }
     */
    public function __construct($data = NULL) {
        \Reatang\GrpcPHPAbstract\Tests\Mock\TestServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string trace = 1;</code>
     * @return string
     */
    public function getTrace()
    {
        return $this->trace;
    }

    /**
     * Generated from protobuf field <code>string trace = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTrace($var)
    {
        GPBUtil::checkString($var, True);
        $this->trace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string baggage = 2;</code>
     * @return string
     */
    public function getBaggage()
    {
        return $this->baggage;
    }

    /**
     * Generated from protobuf field <code>string baggage = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBaggage($var)
    {
        GPBUtil::checkString($var, True);
        $this->baggage = $var;

        return $this;
    }

}

