<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_server.proto

namespace Reatang\GrpcPHPAbstract\Tests\Mock\PB;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>reatang.grpc_php_abstract.tests.mock.PingResponse</code>
 */
class PingResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string pong = 1;</code>
     */
    protected $pong = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pong
     * }
     */
    public function __construct($data = NULL) {
        \Reatang\GrpcPHPAbstract\Tests\Mock\TestServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string pong = 1;</code>
     * @return string
     */
    public function getPong()
    {
        return $this->pong;
    }

    /**
     * Generated from protobuf field <code>string pong = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPong($var)
    {
        GPBUtil::checkString($var, True);
        $this->pong = $var;

        return $this;
    }

}

