<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_server.proto

namespace Reatang\GrpcPHPAbstract\Tests\Mock\PB;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>reatang.grpc_php_abstract.tests.mock.SomeMap</code>
 */
class SomeMap extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, string> map1 = 1;</code>
     */
    private $map1;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $map1
     * }
     */
    public function __construct($data = NULL) {
        \Reatang\GrpcPHPAbstract\Tests\Mock\TestServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, string> map1 = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMap1()
    {
        return $this->map1;
    }

    /**
     * Generated from protobuf field <code>map<string, string> map1 = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMap1($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->map1 = $arr;

        return $this;
    }

}

