<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_server.proto

namespace Reatang\GrpcPHPAbstract\Tests\Mock;

class TestServer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
µ
test_server.proto$reatang.grpc_php_abstract.tests.mock"
PingRequest
ping (	"
PingResponse
pong (	"
OTelRequest".
OTelResponse
trace (	
baggage (	2ö

TestServerÑ
Ping1.reatang.grpc_php_abstract.tests.mock.PingRequest2.reatang.grpc_php_abstract.tests.mock.PingResponse"Ç”‰ì"
/grpc/ping:*Ñ
OTel1.reatang.grpc_php_abstract.tests.mock.OTelRequest2.reatang.grpc_php_abstract.tests.mock.OTelResponse"Ç”‰ì"
/grpc/otel:*B[Z./mock¬PB\\ "Reatang\\GrpcPHPAbstract\\Tests\\Mock–‚"Reatang\\GrpcPHPAbstract\\Tests\\Mockbproto3'
        , true);

        static::$is_initialized = true;
    }
}

